### ISSUE TITLE
Getting more than 100 songs from playlist

### ISSUE THREAD

**Issue by JDOG6869** [Luuk-Dev/Spotify-Info#1]
Was wondering how to get more than 100 songs using the getPlaylist function?

**Comment by Luuk-Dev** [comment]
Hey JDOG6869!

I have just released a new version which transforms the `tracks` Array of the ApiPlaylist class into an object. Within this object, two new functions have been added, the `nextPage` and `previousPage` functions, which you can use to request up to a hundred extra tracks of the same playlist. This does return a new instance of the ApiPlaylist class which means that you won't be able to view the previous tracks in the array provided by the ApiPlaylist class and you would need to cache them if you'd like to view the previous provided tracks.

Kind regards,

Luuk
